### ISSUE TITLE
CSV exporting

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#226]
Still using the "normal" log-in/sample document set-up, I exported the record as a CSV file.  It lacks an entry for the language field.  Now when I look at the PSAP website record for this item, it also does not list a language.  However, both the EAD and DC records _do_ list the language.  

There seem to be two things then here.  One is that the CSV file, which does have a column set aside for language, isn't filling out that spot, even though (given the EAD and DC records) it should have the data available to do so.  The second is that the record on the PSAP website doesn't provide a language header nor specify a language under that header for items/collections, which is what it should be doing and despite already having the data to fill in under a language header.

**Comment by adolski** [comment]
What's happening here is that if the resource doesn't have a language, we are showing the institution's language in its place in the EAD and DC. (This was a @rnedge directive from a long time ago.) That is the reason for the absence of the "language" header on the show-resource page. But the absence of a language in the CSV is a bug.

**Comment by areisemann** [comment]
Hmm, but won't users be specifying the language of the items/collections?  I'd say that there should be a language header for the assessment report.  If the language isn't specified by the person assessing the item/collection, then couldn't a value of "unknown" be the default?

**Comment by adolski** [comment]
Users can specify a language for an item/collection, but they can also opt to use "that of institution," which is the default if they don't specifically set it.

We could make the language header always appear, though that behavior would be inconsistent with the other resource properties. Since a lot of them are optional (see the "Optional Info" section of the resource edit page for what all is available), if we wanted to be consistent, we would potentially be showing a lot of this:

Language
    Unknown
Notes
    None
Subject(s)
    None
So-and-so
    Unknown

etc.
