### ISSUE TITLE
review content of basic help and add links to format ID guide etc.

### ISSUE THREAD

**Issue by jhain** [PresConsUIUC/PSAP#263]
needs to be reviewed AFTER issue #254

**Comment by jhain** [comment]
be sure to include "extent" section for clarity

**Comment by adolski** [comment]
#254 is fixed; work on this issue may commence after doing a git pull.

**Comment by jamieviva** [comment]
@adolski has answered question regarding links in question dependency spreadsheet: The "help" column supports text only. If there are values in the AdvHelp-Doc and AdvHelp-Anchor columns, a "more info" link will appear at the bottom of the hovertip to take you to the corresponding section in the advanced help. One option would be to link to the advanced help, and then refer to the FIDG from there. Otherwise, we will have to add an issue for this feature. @jhain Please advise.

**Comment by jhain** [comment]
I think we just point to advanced help and the FIDG from there.  Seems the simplest.

Sent from an itty-bitty keyboard

On Apr 1, 2015, at 4:41 PM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


@adolski<https://github.com/adolski> has answered question regarding links in question dependency spreadsheet: The "help" column supports text only. If there are values in the AdvHelp-Doc and AdvHelp-Anchor columns, a "more info" link will appear at the bottom of the hovertip to take you to the corresponding section in the advanced help. One option would be to link to the advanced help, and then refer to the FIDG from there. Otherwise, we will have to add an issue for this feature. @jhain<https://github.com/jhain> Please advise.
