### ISSUE TITLE
Add labels to xy axis of assessment report charts

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#281]
vertical: # of items
horizontal: score

also add data label to the bars

**Comment by areisemann** [comment]
Yes, in addition to the X/Y axis issue, my tester today noticed that the values for the Y axis were different (one had integers and the other was in decimals) between the two graphs, which she found very confusing.

**Comment by adolski** [comment]
Axis labels are in place in the HTML and PDF reports.

I'm going to argue we nix the bar labels. They are going to be more complicated than they seem, mainly in terms of layout -- preventing overlap, selectively moving them above or below the bar depending on bar height, dealing with contrast issues when they are over the bar, dealing with them being too wide to fit on the bar, etc. It's easy to slap them onto the chart, but hard to make them look good, and I don't think they add much value even at their best.

Also, they will have to be written twice because the code driving the PDF and HTML charts is completely different. It has been a lot of work just getting the axis labels working.

I will leave this issue open, though -- @jhain, feel free to close it if you agree.

**Comment by jhain** [comment]
totally cool letting that go.  thanks!
