### ISSUE TITLE
link asssessment type primary help to preservation assessments and surveys (FIDG)

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#285]
'more information' not showing up for assessment questions

**Comment by adolski** [comment]
If you type:

`$ rails console`

`q = AssessmentQuestion.find(1)`

Do you see `advanced_help_page: "paper-unbound-originaldoc", advanced_help_anchor: "handlinguse"` in the output?

**Comment by areisemann** [comment]
I'm not sure if you're already aware of this issue, but the advanced help link is missing from the item/sample choice when adding a resource.  The tester I had today went to the basic help but still wasn't sure if sample was what she wanted to do.  However, there was no advanced help link in the basic help bubble for her to use.

**Comment by adolski** [comment]
For all three of the items in the Sample Location, all of the "more information..." links in the assessment form appear for me and work. I have no idea why this wouldn't be working for you and I would need access to the laptop to debug it.

@areisemann, are the "more information" links broken for you too? If so, perhaps I could come over to Oak St. some time and work on this on your laptop?

I would say this wasn't a big deal if it wasn't interfering with usability testing. But the really important thing is that it works in production.

**Comment by areisemann** [comment]
ok, well, we were using the 'UofI Repository for User Testing' that i set up.  within it, she was assessing resources to 'Location at Spurlock Museum'.  when you click on the help button next to the 'Resource Type' (item/collection) when _adding_ the resource, there is no link to advanced help.  when you click on the help button next to the 'Assessment Type' (item-level/sample), there is no link to advanced help.  

in this latter case, the only thing in the bubble is a somewhat unhelpful "Is this collection assessed at the item level or on a sample basis?"  the beta-tester was unsure what was meant by the "sample", and this sentence did not clear up her confusion.  she then looked around for a place to find more information, even trying the glossary before giving up.  her solution was to just go ahead and enter the item (the U-matic tape), which was definitely not chosen on a sample basis (such as we meant by the question), as a 'sample'.  

this indicates potentially two places that links to advanced help could have avoided not only confusion but incorrect entry of a resource.  while the tester ultimately incorrectly identified the resource as a sample while assessing it because the advanced help link was missing from the help bubble, she may have not made this mistake if the advanced help was working when she first added the resource (and looked at the differences between item and collection level assessments).

**Comment by jamieviva** [comment]
Just to clarify @areisemann and @adolski -- advanced help as such does not exist for the resource type question or for resource creation questions. It has always only existed for assessment questions following USE/ACCESS. We had discussed linking to a couple advanced help pages in resource creation, like a supplementary 'Date' segment, but have not implemented that yet (though the content is written).
