### ISSUE TITLE
Add text for expanding optional section

### ISSUE THREAD

**Issue by jamieviva** [PresConsUIUC/PSAP#291]

**Comment by areisemann** [comment]
This is a good idea.  From my most recent beta-testing, the user would have found it helpful to have some brief descriptive text about the purpose/function of optional information on the add resource pop-up.

**Comment by jamieviva** [comment]
"Optional information does not affect a resource's score. Click to expand."

**Comment by adolski** [comment]
Sounds good to me.

**Comment by areisemann** [comment]
I think something like this would work better: "Optional information does not affect a resource's score.  Information entered in this area will be used to generate descriptive records and metadata for assessed items and collections."  Otherwise, users still won't have a good idea of the purpose (and the value) of providing optional information.

**Comment by jamieviva** [comment]
In-line notice: "Optional information does not affect a resource's score. Click to expand."
Add help button with this notice: "Optional information does not affect a resource's score. Information entered in this area will be used to generate descriptive records and metadata for assessed items and collections."
