### ISSUE TITLE
Resource search isn't working properly

### ISSUE THREAD

**Issue by areisemann** [PresConsUIUC/PSAP#297]
From my user-testing earlier today, there were some significant issues with the resource search.  In part, it seems like this function is broken (#s 2-4).  

1) There does not seem to be a way to find answers to questions like: how many items are assessed?  how many of each specific format (vhs) and general format type (videotape) are there?

2) The "any" function/choice does not work at all.  You cannot select "any" for any of the choices and then be able to still search through your institution's resources.  

3) It was ridiculously difficult to search/find the videotape (U-matic SP; assessed) she added to the collection as was it to find the videotape (VHS, unassessed) I had entered into the repository under another collection.  She was logged in as an administrator so she should have been able to search a) all users b) all materials c) all videotapes.  However, she was forced to know the specific user, specific location/collection, specific media type, and then by the specific format type itself, which she would also have to know was already part of the collection/etc.  

4) You cannot search for unassessed items.

**Comment by adolski** [comment]
1) If you wanted to find out how many items have been assessed, you would choose "Resource Type -> Item" and "Assessed" -> "Assessed." (Notably, you can't choose "Resource Type -> Any" because only items can be assessed.) You could then filter that by repository, format, etc. Also, I added a count above the results table.

2) The "any" radios just mean that resources will not be filtered by their "resource type" or "assessed" properties. And they do work for me with all combinations of repository, format, user, etc. However, I did find a bug where when you select the default language of the institution, no resources would be found, because the search would be looking for resources with that language specifically ascribed to them, when they are supposed to be inheriting it. Fixed.

3) I cannot reproduce this -- if I add a Betamax item, and then select "Resource Type -> Item" and "Format -> Betamax", it comes up.

4) I cannot reproduce this -- it should be possible by selecting "Resource Type -> Item" and then "Assessed -> Not Assessed."

**Comment by adolski** [comment]
Also, considering strictly the usability of the resource search, which I think this issue touches on, it's a somewhat complex feature that does require a certain amount of knowledge of how the application works. I wouldn't expect a beginner to be able to jump in and master it right away. I think it's already about as simple as it could be given all that it does and all the use cases it needs to support: "find X by arbitrary criteria Y."
