### ISSUE TITLE
Media query / Left nav bar discrepancy (FIDG)

### ISSUE THREAD

**Issue by rnedge** [PresConsUIUC/PSAP#307]
In the FIDG, the left nav bar reaches into page content when the browser window is scale below ~985px

![screen shot 2015-06-15 at 2 04 51 pm](https://cloud.githubusercontent.com/assets/6729329/8166773/ea313aca-1367-11e5-810d-10b9a70daa66.png)

**Comment by rnedge** [comment]
Now having a different, but more persistent issue:
at ~670px wide:
![screen shot 2015-06-18 at 10 59 21 am](https://cloud.githubusercontent.com/assets/6729329/8234383/a16823d2-15a9-11e5-88d7-6dc3ead29810.png)

at ~920px wide:
![screen shot 2015-06-18 at 10 59 38 am](https://cloud.githubusercontent.com/assets/6729329/8234396/ade8b0ae-15a9-11e5-879e-e35013e34f99.png)

**Comment by adolski** [comment]
#1 is expected behavior - the columns use the [col-sm-3 and col-sm-9 bootstrap classes](http://getbootstrap.com/css/#grid).

I can't reproduce #2 in Chrome, Safari, or Firefox. What browser/OS is this happening in?

**Comment by rnedge** [comment]
2 is happening in Firefox (38.0.1) and OS X 10.9.5

**Comment by adolski** [comment]
I think it's just your setup. Otherwise, probably [processes running slowly due to weak power supply](http://pages.cs.wisc.edu/~ballard/bofh/bofhserver.pl).

Try this:

1. bundle exec rake assets:clobber
2. restart bin/rails server
3. clear browser cache
4. shift+reload the page

If that doesn't work, try the usual update rigamarole (git pull etc.).

**Comment by rnedge** [comment]
Excellent. Gotta be that weak power supply. Or that internet bill. Been hearing a lot about these roving internet shortages today...

It's all good now, having cleared the cache.
