### ISSUE TITLE
Improve feedback during the sign-up process

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#323]
1) If a user who is a) not enabled and b) has a null last sign-in date attempts to sign in, display a flash message saying something like, "your account has been confirmed, but it has not yet been enabled by PSAP staff. We try to do this as quickly as possible. If you have been waiting a while, please feel free to contact us."

2) After a user confirms, instead of a flash message, display a message in large type explaining what is happening. "Your account is confirmed, but before you can sign in, it needs to be reviewed by PSAP staff. You will receive an email when you can sign in."

**Comment by jhain** [comment]
I'm good with either, but agree we need something to get their attention!!

Sent from an itty-bitty keyboard

On Jul 31, 2015, at 9:59 AM, adolski <notifications@github.com<mailto:notifications@github.com>> wrote:


1) If a user who is a) not enabled and b) has a null last sign-in date attempts to sign in, display a flash message saying something like, "your account has been confirmed, but it has not yet been enabled by PSAP staff. We try to do this as quickly as possible. If you have been waiting a while, please feel free to contact us."

2) After a user confirms, instead of a flash message, display a message in large type explaining what is happening. "Your account is confirmed, but before you can sign in, it needs to be reviewed by PSAP staff. You will receive an email when you can sign in."
