### ISSUE TITLE
Missing Images - Adv Help pages (Objects)

### ISSUE THREAD

**Issue by spelczar** [PresConsUIUC/PSAP#356]
A slew of images aren't showing up in the 4 Advanced Help sections for the 4 object types. The images ARE in the AdvHelp Ext images folder and in the HTML, and they didn't show up on Alex's list of missing images from the last ingest - so not sure what is going on. When the Advanced Help was first loaded into the staged site - all the images worked just fine. Here are just some of the images that are missing -- these are missing from all 4 advanced help sections: glasspiecescustombox.jpg; earthenwarebowlcracked.jpg; moldyrecordingcontainer2.jpg; and roachleavings.jpg. There are additional images missing from each material type's Adv Help too -- I can provide you with a list of the specific photos if needed. Just let me know!

**Comment by adolski** [comment]
I believe this is caused by a difference in the filename case between the HTML files and images. For example, the following tag:

`<img src="images/moldyrecordingcontainer2.jpg" alt="Mold can grow on object enclosures and supports as well" />`

refers to an image named `MoldyRecordingContainer2.jpg` (note the capitalization). This will work on Windows where case is not important, but will not work anywhere else.

Options are to rename the files to match the tags, or rename the filenames in the tags to match the files.

**Comment by spelczar** [comment]
The weird thing is that not all the missing images have upper vs. lower case discrepancies between the HTML files and the image file - but I went ahead and fixed the HTML for the ones that were different, so we'll see if they're working after the next HTML re-ingest. Thanks.

**Comment by adolski** [comment]
Yes, they're all fixed. Will take effect on psap-stage after the next re-ingest.
