### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by adolski** [PresConsUIUC/PSAP#62]

**Comment by areisemann** [comment]
I'm not sure what needs to be done here specifically (i.e. one particular section needs help).  Why is this up here on Github?

**Comment by adolski** [comment]
This is the user manual content in G:\AcqCatPres\PSAP\Design\HTML\UserManual
which will appear at http://psap.library.illinois.edu/manual. You can see what this looks like currently by navigating to http://localhost:3000/manual. Unless we can "finish" the user manual by the end of Feb., we will need to put up a notice on that page indicating that the manual is still under development.

**Comment by adolski** [comment]
Also, I see that you have been working on this recently. I noticed that it might be an improvement to make the web browser screenshots about half as wide and 2/3 as tall -- just an idea.

**Comment by areisemann** [comment]
Well, I've already got a working draft of the user manual in the html folder.  I think that for most of it, we can have it finished by the end of February no problem.  Once we finish the beta-testing in several months, we may need to update material in some of the screenshots (and perhaps the related walkthroughs), but I don't think overall it's a problem.  

As for the screenshots, yea, they are wider than I'd like.  Right now, I was just focused on getting them in so I could get a better feel for the flow/lay-out of the manual.

**Comment by adolski** [comment]
I'm ready to import the user manual content; should I be importing usermanual.html or User Manual in MSWord JHT edits.docx?

**Comment by jhain** [comment]
Neither!  Not done yet!!! Thx!

Sent from an itty-bitty keyboard

On Jun 16, 2015, at 10:54 AM, adolski <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm ready to import the user manual content; should I be importing usermanual.html or User Manual in MSWord JHT edits.docx?

**Comment by jhain** [comment]
are we keeping the user manual walkthroughs? I am pointing to different user manual features in the videos, and want to know if I can direct users to these. Additionally, I am using the anchors in /PSAP/Design/HTML/UserManual/usermanual.html to provide anchored links-- so please don't change those!

I was thinking that retaining a section on why institution and location and resources need to be assessed would be useful, I don't ever really go into context for that in the videos, I just emphasize that it has to be done, and I think it would be helpful to point users to the manual if they're confused about that.

in terms of accessibility, it would be better to have information in several places (one of which being written) instead of contained only in a video. those sections in the user manual wouldn't have to be long, but i think it does makes sense to keep a description/explanation of them in it.

**Comment by jhain** [comment]
OK, i'm calling this done.  It still needs formatting corrected in places and images updated in some places, but i am SO SLOW at doing this all in HTML and i don't want to hold this up any longer. The information provided is, i think, accurate enough, at least for the soft release. I will continue to pick away at editing for the final release, but for now i think it's got to be good enough. Sorry for the holdup.

**Comment by adolski** [comment]
Thanks. Please hold off on any more edits until launch, as I will need to make some myself.

**Comment by jhain** [comment]
Sure thing.

Sent from an itty-bitty keyboard

On Jun 24, 2015, at 7:15 PM, adolski <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks. Please hold off on any more edits until launch, as I will need to make some myself.
